// JAVASCRIPT FRAMEWORK/VUE/CODES/todoList/src/components/NavBar.vue
<script setup>
import { RouterLink, RouterView } from 'vue-router'
</script>
<template>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">TODO LIST MADE BY VUE.JS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <router-link to="/" class="nav-link active" aria-current="page">Home</router-link>
        </li>
        <li class="nav-item">
            <router-link to="/about" class="nav-link active" aria-current="page">About</router-link>
        </li>
      </ul>
    </div>
  </div>
</nav>
</template>
<style scoped>
</style>

// JAVASCRIPT FRAMEWORK/REACT/CODES/todolist/src/components/NavBar.js
import { Link } from "react-router-dom"

export default function NavBar(){
    return(
        <>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    {/*eslint-disable-next-line*/}
    <a class="navbar-brand" href="#">TODO LIST MADE BY VUE.JS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <Link to="/" class="nav-link active">Home</Link>
        </li>
        <li class="nav-item">
            <Link to="/about" class="nav-link active">About</Link>
        </li>
      </ul>
    </div>
  </div>
</nav>
        </>
    )
}
